---
# tasks file for dhcpd

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ default }}.yml"
  tags: dhcp

- name: Install packages
  package:
    pkg: "{{ item }}"
    state: "{{ dhcp_packages_state }}"
  with_items: "{{ dhcp_packages }}"
  tags: dhcp


- name: Install dhcp interface config file
  template:
    src: etc_dhcp_ifcfg.j2
    dest: "{{ dhcp_ifcfg_file }}-{{ dhcp_interface_name }}"
  notify: restart network
  tags: dhcp

- name: Set config directory perms
  file:
    path: "{{ dhcp_config | dirname }}"
    state: directory
    mode: 0755
  tags: dhcp

- name: Install config file
  template:
    src: etc_dhcp_dhcpd.conf.j2
    dest: "{{ dhcp_config }}"
    owner: root
    group: root
    mode: 0644
    validate: 'dhcpd -t -cf %s'
  notify: restart dhcp
  tags: dhcp

- name: "Ensure service is {{ dhcp_global_server_state | default('started') }}"
  service:
    name: "{{ dhcp_service }}"
    state: "{{ dhcp_global_server_state | default('started') }}"
    enabled: true
  tags: dhcp
  