galaxy_info:
  author: Alexei Sukharev
  description: Ansible Common configuration

  license: BSD

  min_ansible_version: 1.2

  platforms:
  - name: CentOS
    versions:
    - 7

  galaxy_tags: 
    - system

dependencies: []
