- name: "Defining interfaces for zone {{ zone.name }}"
  firewalld:
    zone: "{{ zone.name }}"
    interface: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ zone.interfaces }}"
  notify: Reload firewalld
  tags:
    - base
    - firewalld

- name: "Enabling services for zone {{ zone.name }}"
  firewalld:
    zone: "{{ zone.name }}"
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ zone.services }}"
  notify: Reload firewalld
  tags:
    - base
    - firewalld
