---
# tasks file for common

- name: OS specific initializing
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ default }}.yml"
  tags:
    - base

- name: Set hostname
  hostname:
    name: "{{ base_hostname }}"
  tags:
    - base
    - network

- name: Backup repository files
  block:
    - name: Making a repository backup directory
      file:
        path: "{{ base_repository_dir }}/ansible_backup"
        state: directory

    - name: Finding existing repository files
      find:
        paths: "{{ base_repository_dir }}/"
        patterns: "*.repo"
      register: files_to_move

    - name: Backuping repository files
      copy:
        src: "{{ item.path }}"
        dest: "{{ base_repository_dir }}/ansible_backup/"
        remote_src: yes
      with_items: "{{ files_to_move.files }}"
      loop_control:
        label: "Backup repo-file: {{ item.path }}"

    - name: Removing repository files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_move.files }}"
      loop_control:
        label: "Remove repo-file: {{ item.path }}"
  when:
    - base_use_local_repositories
    - base_use_only_local_repositories
  tags:
    - base
    - repository

- name: Import RedHat Tasks
  import_tasks: RedHat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
  tags:
    - base

- name: Include firewall setup playbook
  include_tasks: firewall_zone.yml
  loop: "{{ base_firewall_zones }}"
  loop_control:
    loop_var: zone
  notify: Reload firewalld
  tags:
    - base
    - firewalld
    - network

- name: Install base packages
  package:
    pkg: "{{ item }}"
    state: installed
  with_items: "{{ base_packages }}"
  tags:
    - base