- name: Configure network interfaces
  template:
    src: ifcfg.j2
    dest: "{{ base_netscripts_dir }}/ifcfg-{{ item.name }}"
  with_items:
    - "{{ base_interfaces }}"
  notify: Restart network
  tags: 
    - base
    - network

- name: Installing local YUM-repository`
  yum_repository:
    name: "{{ item.id }}"
    description: "{{ item.name }}"
    file: local-repos
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck | default('0') }}"
    enabled: "{{ item.enabled | default('1') }}"
  with_items: "{{ base_yum_local_repositories }}"
  when: base_use_local_repositories
  loop_control: 
    label: "Add repository: {{ item.name }}"
  tags: 
    - base
    - repository
