---
# handlers file for dhcpd

- name: restart network
  service:
    name: network
    state: restarted

- name: restart dhcp
  service:
    name: "{{ dhcp_service }}"
    state: "{{ (dhcp_global_server_state | default('started') == 'started') | ternary('restarted', 'stopped') }}"
